### ISSUE TITLE
Hylätty suoritus vaikuttaa tehtävän interpolointiin

### ISSUE THREAD

**Issue by pholm** [partio-scout/kipa#2]
Jos vartiolle syötetään tehtävästä H, vaikuttaa se muiden vartioiden tuloksiin interpolointitehtävässä.

**Comment by TileHalo** [comment]
Kuuluu laskentaan. Pitää muuttaa tuloksien syötössäse niin, että H=0 tai MAX, olettaen, että tulosta kohdellaan näin.

**Comment by vaaralav** [comment]
Eikö se hylätty suoritus pitäis olla kokonaan poissa siitä joukosta, jolle lasketaan mediaania?

**Comment by TileHalo** [comment]
Eiku joo.

**Comment by ZeiP** [comment]
Korjattu.
