### ISSUE TITLE
Staattiset tiedostot eivät toimi oletuskonfiguraatiolla

### ISSUE THREAD

**Issue by villevuor** [partio-scout/kipa#20]
Jos seuraa esim. [Mac OS asennusohjeita](https://sites.google.com/site/kisapalvelukipa/kaeytae-ja-asenna), asennus toimii mutta mediatiedostot palauttavat 404. Asia korjaantuu jos vaihtaa tiedostoon `settings.py` riville ku `DEBUG=True`.

En tunge djangoa/kipaa riittävästi että tietäisin mistä johtuu, mutta johonkin voisi ehkä korjata tai vähintään kirjata ylös, aika kauan voi mennä selvitellessä 😅

**Comment by pholm** [comment]
Ilmeisesti johtuu /web/urls.py configuraatiosta, jossa staattiset tiedostot tarjoillaan eri tavalla debug-tilassa. Imo tämän voisi tehdä myös tuotannossa samalla tavalla: jossain lähteissä suositellaan staattisille tiedostoille erillistä palvelinohjelmaa, mutta se ei liene relevanttia Kipan kohdalla.

![image](https://user-images.githubusercontent.com/1903693/135912844-84077215-3211-435b-a566-5cf56249deee.png)

**Comment by villevuor** [comment]
Joo, hyvä löytö. Joka tapauksessa asennusohjeisiin voisi tarkentaa, miten pitäisi tehdä

**Comment by ZeiP** [comment]
Joo, yleensä suositellaan että tuotantoasennuksissa tiedostot palveltaisiin suoraan HTTP-palvelimella. Itselläni on tästä ajossa tuotantoversio jossa on Nginx edessä, mutta toki monet varmaan ajavat kisakohtaisia virtuaali- tms. ympäristöjä joissa tuo ei ehkä ole relevanttia. Dokumentaatiota on ehdottomasti ainakin syytä parantaa ja tehdä mahdollisimman helpoksi tiedostojen palveleminen suoraan Djangon kautta. Mietin että pitäisikö tuolle luoda oma asetus sen sijaan että käyttää DEBUGia, jolla on myös muita vaikutuksia, ja laittaa vaikka sen oletuksena päälle?

**Comment by ZeiP** [comment]
Tämä tulikin näemmä nyt samalla korjattua, eli nyt on SERVE_MEDIA-asetus erikseen joka määrittää palveleeko Django tiedostot. Docker-versiossa tuo on päällä jolloin koko homma toimii oletuksena paketista.
