### ISSUE TITLE
Dokumentaation päivitys

### ISSUE THREAD

**Issue by villevuor** [partio-scout/kipa#25]
Kipan dokumentaatio on nyt varsin levällään.

Käytössä on mm.:
- Google Sites: https://sites.google.com/site/kisapalvelukipa/home
- Github Pages: https://partio-scout.github.io/kipa/
- SourceForge
- Tämä Github-repository
- Erinäisiä Google Docs -vinkkejä asennukseen linkattuina kolmeen ylläolevaan

Ehdotan, että suljetaan kaikki muut paitsi tämä Github-repository, ja siirretään ohjeet tämän repon wikiin. Hyötyjä: kaikki yhdessä paikassa, mahdollisuus keskusteluun (discussions, esim. voisi jakaa hyödyllisiä koodisnippettejä), käyttäjien havaitsemat bugit toivottavasti dokumentoitaisiin jonnekin (esim. issues). Githubiin saa myös releases-osioon tallennettua käännetyt asennusohjelmat.

Pieni miinus se, että Github on vähän "tekninen", mutta jos nyt ollaan rehellisiä, Kipan kanssa toimiminen vaatii aina vähän teknistä osaamista.

Voidaan Petruksen kanssa tehdä tämä jos saadaan vihreää valoa.

**Comment by ZeiP** [comment]
Joo, tuo SourceForge ja Google Sites ovat vanhentuneita – itse asiassa SF-projekti näkyy olevankin jo suljettu, pistin sen ehkä kiinni kun sain migraation Gitiin tehtyä. GitHub Pagesiin on siirretty tuolla Sitesissa olevat sisällöt, koska en ole saanut niihin päivitysoikeuksia (ainakaan muistaakseni), voisin kysellä josko saisin oikat sulkea tuon.

Dokumentaatiota olisi todella arvokasta koota yhteen paikkaan, wiki on oikein toimiva alusta sille. Jättäisin lisäksi tuon Github Pagesin olemaan nykyisenlaisena eli enemmänkin ”markkinointisivustona” – vaikka päivittäähän sekin toki pitäisi. Eli jos saatte koottua dokumentaatiot Githubin wikiin sekä Sitesista (jos siellä jotain arvokasta on) että muista lähteistä ja poisteltua vanhentuneet linkit Sitesiin / SourceForgeen niin hienoa!

**Comment by pholm** [comment]
Poistin tosiaan Sourceforgen viikonloppuna, oon kanssa pyytänyt Sitesin oikeuksia. Pistin nyt Kipan ap. kehittäjille viestiä, josko saisin oikeudet sitä kautta. 

Kannatan kyllä Villen ehdotusta siitä, että kerättäisiin kaikki rönsyt tänne md-tiedostoina. Editoinnin kynnys myös pienenisi samalla.

**Comment by ZeiP** [comment]
Aa sä poistit sen, mietinkin että eikös se jäänyt multa roikkumaan kun siirtelin kamat tänne Githubin puolelle aikoinaan. Ok. Hyvä tietää että kyselit jo oikeuksia, niin en lähde turhaan kyselemään samaa asiaa.

**Comment by pholm** [comment]
Joo :) Sain itseasiassa heistä yhden nyt kiinni ja oikeudet on. Tässä .zip tiedosto sivun arkistosta, suljen sivun nyt. 

[kisapalvelukipa.zip](https://github.com/partio-scout/kipa/files/7285283/kisapalvelukipa.zip)

**Comment by ZeiP** [comment]
Tämä taisi tulla kuntoon, eikös?

**Comment by ZeiP** [comment]
Siirtelin asennusohjeet tuonne wikin puolelle, mikä jäi tässä vielä kesken.
