### ISSUE TITLE
Tuki saman nimisille vartioille samassa sarjassa

### ISSUE THREAD

**Issue by vaaralav** [partio-scout/kipa#3]
Nyt KIPA sallii saman nimisten vartioiden luomisen, mutta tehtävien tuloksia syötettäessä syötetty tulos kopioituu kaikille saman nimisille vartioille.

**Comment by ZeiP** [comment]
Koitin toistaa tätä, mutta en saanut uusimmalla masterilla tällaista ongelmaa toistumaan. Suljen tiketin, mutta kommentoikaa tähän jos vielä joku saa ongelman toistettua.

**Comment by Pena86** [comment]
Ja tässä äskeiseen lisätty kaksi (ei saman nimistä, mutta) samannumeroista vartiota, jotka saavat pistesyötteeksi aina jälkimmäisen arvon. Samalla nimellä, eri numerolla olevia vartioita en saanut toimimaan väärin
Jokatapauksessa, viimeistään paperityön helpottamiseksi olisi ohjelmaan hyvä lisätä tarkistus, että samassa kisassa ei ole samannimistä tai numeroista vartiota.

[tupa_tietokanta_samannimiset_vartiot.zip](https://github.com/partio-scout/kipa/files/1471481/tupa_tietokanta_samannimiset_vartiot.zip)
