### ISSUE TITLE
Kipan julkaisu konttina

### ISSUE THREAD

**Issue by happosade** [partio-scout/kipa#78]
Repoista löytyy jo valmiiksi dockerfile. Kipaa voisikin julkaista valmiiksi paketoituna konttina esim ghcr.io'ssa.

Tämä helpottaisi kipan käyttämistä omalla koneella, kun kaikki riippuvuudet saa näppärästi yhtenä pallerona.

En varsinaisesti ole koskaan sen pahemmin pythonia paketoinut, mutta pikaisella vilkaisulla tarvittavat muutokset ovat kohtalaisen pienet:

- varmista, että kontti buildaa oikein
- julkaise ghcr.io'hon

Jos halutaan kikkailla pidemmälle:

- Github action tekemään uudet julkaisut
- Minimal (multistage?) build pienemmän kontin luomiseksi
- Dokumentaatio, esim kipa.db'n mounttaamiseksi konttiin

**Comment by ilesoft** [comment]
Tämähän on jo melkein levylautasella...
https://github.com/partio-scout/kipa/pull/73
Tuonne voi kertoa jos ehdotetusta toteutuksesta tulee jotain ajatuksia.

**Comment by ilesoft** [comment]
Nyt ghcr.io:sta löytyy tagilla `develop` [kuva](https://github.com/partio-scout/kipa/pkgs/container/kipa/325731646?tag=develop), jota voi testailla. Jahka tuota päästää testaamaan jossain oikeassa kisassa niin jossain lähitulevaisuudessa™ saadaan varmaan vähän virallisempi julkaisu.
